FROM zookeeper:latest
RUN apt update && apt upgrade
RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y build-essential
RUN apt install -y libglib2.0-dev libpq-dev
RUN pip3 install -r requirements.txt