FROM apache/airflow:2.2.3
ENV AIRFLOW_HOME /usr/local/airflow
ENV AIRFLOW_CONFIG /usr/local/airflow/airflow.cfg
RUN apt update && apt upgrade && apt install -y python3 && apt install -y python3-pip && apt install -y build-essential && apt install -y libglib2.0-dev libpq-dev && pip3 install -r requirements.txt
